package com.github.hykes.codegen.gui;

import com.github.hykes.codegen.model.IdeaContext;
import com.github.hykes.codegen.model.Table;
import com.github.hykes.codegen.parser.DefaultParser;
import com.github.hykes.codegen.parser.Parser;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.ui.MessageType;
import com.intellij.ui.ScrollPaneFactory;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 * @author: hehaiyang@terminus.io
 * @date: 2017/12/19
 */
public class SqlEditorPanel {

    private static final Logger LOGGER = Logger.getInstance(SqlEditorPanel.class);

    private JPanel rootPanel;
    private JLabel tipLab;
    private JButton buttonCancel;
    private JButton buttonOk;
    private JTextArea sqlTextArea;
    private JPanel sqlPanel;
    private JPanel actionPanel;

    public SqlEditorPanel(IdeaContext ideaContext) {
        $$$setupUI$$$();

        buttonOk.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    String sqls = sqlTextArea.getText().trim();

                    Parser parser = new DefaultParser();
                    List<Table> tables = parser.parseSQLs(sqls);

                    if (tables.isEmpty()) {
                        setTips(true, "Error, please check sql format !");
                        return;
                    }

                    ColumnEditorFrame frame = new ColumnEditorFrame();
                    frame.newColumnEditorBySql(ideaContext, tables);
                    frame.setSize(900, 500);
                    frame.setAlwaysOnTop(false);
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    frame.setResizable(true);

                } catch (Exception ex) {
                    LOGGER.error(ex.getMessage());
                } finally {
                    disable();
                }
            }
        });
        buttonCancel.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                disable();
            }
        });

        this.rootPanel.registerKeyboardAction(e -> disable() , KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);

    }

    private void disable() {
        $$$getRootComponent$$$().getRootPane().getParent().setEnabled(false);
        $$$getRootComponent$$$().getRootPane().getParent().setVisible(false);
    }

    private void setTips(boolean operator, String tips) {
        tipLab.setText(tips);
        tipLab.setVisible(operator);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        rootPanel = new JPanel();

        sqlTextArea = new JTextArea();
        sqlTextArea.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        rootPanel.add(ScrollPaneFactory.createScrollPane(sqlTextArea), BorderLayout.CENTER);

        tipLab = new JLabel("Input sql .",
                MessageType.INFO.getDefaultIcon(), SwingConstants.LEFT);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("TestForm");
        frame.setContentPane(new SqlEditorPanel(null).rootPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel.setLayout(new BorderLayout(0, 0));
        actionPanel = new JPanel();
        actionPanel.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(actionPanel, BorderLayout.SOUTH);
        tipLab.setText("Input sql .");
        actionPanel.add(tipLab, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonOk = new JButton();
        buttonOk.setText("OK");
        actionPanel.add(buttonOk, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        actionPanel.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sqlPanel = new JPanel();
        sqlPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.add(sqlPanel, BorderLayout.CENTER);
        sqlPanel.add(sqlTextArea, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
